### ISSUE TITLE
prettyPrint does not work for Bits

### ISSUE THREAD

**Issue by paulo-g** [etingof/pysnmp#79]
I'm trying to prettyPrint a Bits object, and I get:
```
  File "/usr/lib/python2.7/site-packages/pyasn1/type/base.py", line 380, in prettyPrint
    return self.prettyOut(self._value)
  File "/usr/lib/python2.7/site-packages/pysnmp/proto/rfc1902.py", line 660, in prettyOut
    name = self.__namedValues.getName(i * 8 + 7 - j)
AttributeError: 'Bits' object has no attribute '_Bits__namedValues'
```

Using pysnmp==4.3.9.
This was working fine in previous versions (4.3.2).

**Comment by etingof** [comment]
Thank you for your report!

This is hopefully fixed in the upcoming [4.3.10](https://github.com/etingof/pysnmp/tree/release-4.3.10).

Feel free to re-open this issue if the fix does not work for you.
