### ISSUE TITLE
TypeError: prettyIn() got an unexpected keyword argument 'namedValues'

### ISSUE THREAD

**Issue by kaihil** [etingof/pysnmp#113]
Hi (and sorry for the bad topic name, i don't know any better),

I have problems polling the SNMP object `CISCO-ENTITY-REDUNDANCY-MIB::ceRedunMbrStatusCurrent`. The method `Bits::clone(...)` in `pysnmp/proto/rfc1902.py`, line 612 throws `TypeError: prettyIn() got an unexpected keyword argument 'namedValues'`. It looks like `self.prettyIn()` is not referring to `Bits::prettyIn()`, but actually to `TextualConvention::prettyIn()`, which doesn't have a parameter `namedValues`, which would be the reason for the exception.

The error occurs on the latest pysnmp 4.4.2, but its working on 4.3.8 (with pyasn1==0.2.3). (4.3.9 throws another error) I guess it has something to do with this commit, although it stops working on earlier versions: https://github.com/etingof/pysnmp/commit/0f32c00d89eae2f86b2282ffc50805e059be5492#diff-2b14f165b1eb70bab6b887073bab16b1

I attached an example script performing a simple bulkwalk on `CISCO-ENTITY-REDUNDANCY-MIB::ceRedunMbrStatusCurrent`. A minimal `public.snmp_rec` file for "snmpsim" and the corresponding MIB file are also attached:
[redun-example-bulkwalk.zip](https://github.com/etingof/pysnmp/files/1510409/redun-example-bulkwalk.zip)

# Prerequisites
## env438:
```
$ pip install pyasn1==0.2.3 pysnmp==4.3.8 pysnmp-mibs
$ pip freeze
ply==3.10
pyasn1==0.2.3
pycryptodome==3.4.7
pysmi==0.2.2
pysnmp==4.3.8
pysnmp-mibs==0.1.6
```

## env439:
```
$ pip install pyasn1==0.2.3 pysnmp==4.3.9 pysnmp-mibs
$ pip freeze
ply==3.10
pyasn1==0.2.3
pycryptodome==3.4.7
pysmi==0.2.2
pysnmp==4.3.9
pysnmp-mibs==0.1.6
```

## env442:
```
$ pip install pysnmp==4.4.2 pysnmp-mibs
$ pip freeze
ply==3.10
pyasn1==0.4.2
pycryptodomex==3.4.7
pysmi==0.2.2
pysnmp==4.4.2
pysnmp-mibs==0.1.6
```

# Running the example script

When I use pysnmp 4.3.8 and pyasn1 0.2.3 the script works as expected:
```
(env438) $ python redun-example-bulkwalk.py
CISCO-ENTITY-REDUNDANCY-MIB::ceRedunMbrStatusCurrent.1.1.0 = standby
CISCO-ENTITY-REDUNDANCY-MIB::ceRedunMbrStatusCurrent.1.1.1 = protectionProvided
```

When updating to 4.3.9 (leaving pyasn1 at 0.2.3) i get:
```
(env439) $ python redun-example-bulkwalk.py
Traceback (most recent call last):
  File "redun-example-bulkwalk.py", line 31, in <module>
    print(' = '.join([x.prettyPrint() for x in varBind]))
  File "redun-example-bulkwalk.py", line 31, in <listcomp>
    print(' = '.join([x.prettyPrint() for x in varBind]))
  File "/Users/kaihil/pysnmp-test-namedValues/env435/lib/python3.5/site-packages/pyasn1/type/base.py", line 336, in prettyPrint
    return self.prettyOut(self._value)
  File "<string>", line 176, in prettyOut
  File "/Users/kaihil/pysnmp-test-namedValues/env435/lib/python3.5/site-packages/pysnmp/proto/rfc1902.py", line 660, in prettyOut
    name = self.__namedValues.getName(i * 8 + 7 - j)
AttributeError: 'CeRedunMbrStatus' object has no attribute '_Bits__namedValues'
```

And when i use the latest pysnmp 4.4.2 with the latest pyasn1 0.4.2 it throws the following exception:
```
(env442) $ python redun-example-bulkwalk.py
Traceback (most recent call last):
  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 207, in loop
    poll_fun(timeout, map)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 188, in poll2
    readwrite(obj, flags)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 123, in readwrite
    obj.handle_error()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 163, in handle_read
    self._cbFun(self, transportAddress, incomingMessage)
  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/carrier/base.py", line 70, in _cbFun
    self, transportDomain, transportAddress, incomingMessage
  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/entity/engine.py", line 152, in __receiveMessageCbFun
    self, transportDomain, transportAddress, wholeMsg
  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/proto/rfc3412.py", line 486, in receiveMessage
    cachedParams['cbCtx'])
  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/entity/rfc3413/cmdgen.py", line 152, in processResponsePdu
    cbFun(snmpEngine, origSendRequestHandle, None, PDU, cbCtx)
  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/entity/rfc3413/cmdgen.py", line 388, in processResponseVarBinds
    varBindTable, cbCtx):
  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/hlapi/asyncore/cmdgen.py", line 484, in __cbFun
    varBindTable], cbCtx)
  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/hlapi/asyncore/cmdgen.py", line 483, in <listcomp>
    [vbProcessor.unmakeVarBinds(snmpEngine, varBindTableRow, lookupMib) for varBindTableRow in
  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/hlapi/varbinds.py", line 46, in unmakeVarBinds
    varBinds = [ObjectType(ObjectIdentity(x[0]), x[1]).resolveWithMib(mibViewController) for x in varBinds]
  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/hlapi/varbinds.py", line 46, in <listcomp>
    varBinds = [ObjectType(ObjectIdentity(x[0]), x[1]).resolveWithMib(mibViewController) for x in varBinds]
  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/smi/rfc1902.py", line 865, in resolveWithMib
    self.__args[1] = self.__args[0].getMibNode().getSyntax().clone(self.__args[1])
  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/proto/rfc1902.py", line 612, in clone
    args = args and self.prettyIn(args[0], namedValues=namedValues)
TypeError: prettyIn() got an unexpected keyword argument 'namedValues'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "redun-example-bulkwalk.py", line 20, in <module>
    maxCalls=1):
  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/hlapi/asyncore/sync/cmdgen.py", line 554, in bulkCmd
    snmpEngine.transportDispatcher.runDispatcher()
  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 50, in runDispatcher
    raise PySnmpError('poll error: %s' % ';'.join(format_exception(*exc_info())))
pysnmp.error.PySnmpError: poll error: Traceback (most recent call last):
;  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
;  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 207, in loop
    poll_fun(timeout, map)
;  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 188, in poll2
    readwrite(obj, flags)
;  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 123, in readwrite
    obj.handle_error()
;  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
;  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
;  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 163, in handle_read
    self._cbFun(self, transportAddress, incomingMessage)
;  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/carrier/base.py", line 70, in _cbFun
    self, transportDomain, transportAddress, incomingMessage
;  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/entity/engine.py", line 152, in __receiveMessageCbFun
    self, transportDomain, transportAddress, wholeMsg
;  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/proto/rfc3412.py", line 486, in receiveMessage
    cachedParams['cbCtx'])
;  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/entity/rfc3413/cmdgen.py", line 152, in processResponsePdu
    cbFun(snmpEngine, origSendRequestHandle, None, PDU, cbCtx)
;  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/entity/rfc3413/cmdgen.py", line 388, in processResponseVarBinds
    varBindTable, cbCtx):
;  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/hlapi/asyncore/cmdgen.py", line 484, in __cbFun
    varBindTable], cbCtx)
;  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/hlapi/asyncore/cmdgen.py", line 483, in <listcomp>
    [vbProcessor.unmakeVarBinds(snmpEngine, varBindTableRow, lookupMib) for varBindTableRow in
;  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/hlapi/varbinds.py", line 46, in unmakeVarBinds
    varBinds = [ObjectType(ObjectIdentity(x[0]), x[1]).resolveWithMib(mibViewController) for x in varBinds]
;  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/hlapi/varbinds.py", line 46, in <listcomp>
    varBinds = [ObjectType(ObjectIdentity(x[0]), x[1]).resolveWithMib(mibViewController) for x in varBinds]
;  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/smi/rfc1902.py", line 865, in resolveWithMib
    self.__args[1] = self.__args[0].getMibNode().getSyntax().clone(self.__args[1])
;  File "/Users/kaihil/pysnmp-test-namedValues/env442/lib/python3.5/site-packages/pysnmp/proto/rfc1902.py", line 612, in clone
    args = args and self.prettyIn(args[0], namedValues=namedValues)
;TypeError: prettyIn() got an unexpected keyword argument 'namedValues'
```

**Comment by etingof** [comment]
Thank you for your report!

This seems to be a bug in pysnmp which should be fixed by commit 02941722866f0cc8d35dabfb82a3b6c16eabda8b in master.

You test case works for me. I'd appreciate further testing while you are at it. ;-)

Thanks!

**Comment by kaihil** [comment]
Tested it in 4.4.4 and it works. Thanks a lot!
